server:
  port: 8888

spring:
  application:
    name: gatewayserver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
  cloud:
    config:
      enabled: false
      discovery:
        enabled: true
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: auth-ms
            uri: lb://auth_microservice
            predicates:
              - Path=/api/auth/**
          - id: expense-ms
            uri: lb://expense_management_microservice
            predicates:
              - Path=/api/expenses/**

# Eureka configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator management
management:
  endpoints:
    web:
      exposure:
        include: '*'   # Expose all actuator endpoints
  endpoint:
    gateway:
      access: unrestricted

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
