spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/coral-io_realm}
  application:
    name: expense-management-microservice
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:${FILE_UPLOAD_DIR:./uploads}/,classpath:/static/
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:expense_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:112004}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8082}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: '*'

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8087}
    enabled: true

build:
  version: 1.0

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.springframework.security.oauth2: ${LOG_LEVEL_OAUTH2:DEBUG}
    org.springframework.security.oauth2.jwt: ${LOG_LEVEL_JWT:DEBUG}
    org.springframework.web: ${LOG_LEVEL_WEB:DEBUG}
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:DEBUG}