spring:
  security:
    enabled: false  # Add this to disable ALL security
  application:
    name: expense-management-microservice
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:./uploads/,classpath:/static/
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_app
    username: postgres
    password: 112004
    #    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
  sql:
    init:
      mode: always

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

build:
  version: 1.0

file:
  upload-dir: ./uploads
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.web: DEBUG