# Configuration serveur
server.port=8085
spring.application.name=ai-microservice

# Chemin ABSOLU vers le dossier uploads
uploads.dir=C:\\Users\\MSI\\coralio_backend\\uploads
embedding.service.url=http://127.0.0.1:9000/embedding
spring.web.cors.allowed-origins=*

# Dans votre application.properties, assurez-vous que ceci est présent :
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Désactiver sécurité
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Headless mode
java.awt.headless=true
tesseract.datapath=C:\\Program Files\\tessdata
# Langue utilisée par Tesseract (exemple pour l?anglais)
tesseract.language=eng
# Logging
logging.level.com.coralio.ai_microservice=DEBUG
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB