spring.application.name=ai-microservice
server.port=8085

# Chemin ABSOLU vers ton dossier uploads du microservice expense
uploads.dir=C:\\Users\\MSI\\coralio_backend\\uploads
# Ollama
ollama.url=http://localhost:11434
ollama.model=llava-llama3
ollama.options.temperature=0.0
ollama.options.top_p=0.1
ollama.options.top_k=20
ollama.options.repeat_penalty=1.2
ollama.options.num_ctx=4096
ollama.options.num_predict=2048
ollama.options.stop=\n\n\n

# MCP
mcp.max.iterations=10
mcp.timeout.seconds=120

# CORS
spring.web.cors.allowed-origins=*

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ? Désactiver la sécurité
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

java.awt.headless=true
