spring:
  application:
    name: auth_microservice
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

build:
  version: 1.0


